language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.4
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - composer install

script: phpunit